
services:


  frontend:
    build: ./vite_jot
    container_name: jotForm_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - 80:80
    environment:
      - VUE_APP_API_BASE_URL=http://jotForm_backend:3000
    networks:
      - app_network

  mongodb:
    image: mongo:4.4.6
    container_name: jotForm_mongo
    volumes:
      - mongodb-jotf:/data/db
    environment:
      MONGO_INITDB_DATABASE: JotFormDB
    restart: unless-stopped
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: jotForm_backend
    restart: unless-stopped
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    networks:
      - app_network
  


networks:
  app_network:
    driver: bridge

volumes:
  mongodb-jotf: